name: 🚀 Pull Request
description: Submit a new feature, fix, or improvement
title: 'PR: '
labels: ['pull-request']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🔍 Pull Request Summary
        Provide a brief overview of what this PR does.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: What does this PR implement or change?
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 📋 Implemented Actions
        List what you actually did in this PR. Use the button below to add each action or change you made.

  - type: dynamic
    id: actions
    attributes:
      label: Implemented Steps
      add_button_label: Add Step
      fields:
        - type: input
          label: Step
          placeholder: e.g., Added validation to listing model
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## ✅ Pre-Submission Checklist
        Please confirm the following before submitting:

  - type: checkboxes
    id: checklist
    attributes:
      label: Confirm the following:
      options:
        - label: I followed the coding guidelines defined in the project
        - label: I wrote unit/integration tests where applicable
        - label: I tested the feature manually
        - label: I’ve reviewed my changes for security, logic, and edge cases
        - label: I’ve added relevant documentation or comments
        - label: This PR references an open issue (if applicable)

  - type: input
    id: issue
    attributes:
      label: Related Issue #
      placeholder: e.g., #1
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      placeholder: Mention anything reviewers should know before merging
    validations:
      required: false
