name: 🚀 Feature or Task Request
description: Suggest a new feature or backend implementation task
title: 'Feature: '
labels: ['enhancement']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📌 Issue Summary
        Briefly describe the task or feature being proposed.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: Describe the task or feature clearly
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 🛠 Proposed Actions
        List individual steps needed to complete this task.

  - type: dynamic
    id: actions
    attributes:
      label: Proposed Action Steps
      add_button_label: Add Action
      fields:
        - type: input
          label: Action
          placeholder: e.g., Design User model schema
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 📏 Guidelines
        Follow these coding standards:

  - type: checkboxes
    id: guidelines
    attributes:
      label: Coding Standards
      options:
        - label: Use TypeScript for type safety
        - label: Implement proper indexing for performance
        - label: Include comprehensive validation rules
        - label: Write unit tests for all models
        - label: Document schema with diagrams or inline comments

  - type: input
    id: timeframe
    attributes:
      label: Estimated Timeframe
      placeholder: e.g., 5 days
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      placeholder: Mention dependencies, blockers, or any other info
    validations:
      required: false
