name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: artisyn
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mailhog:
        image: mailhog/mailhog
        ports:
          - 1025:1025

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/artisyn?schema=public
      JWT_SECRET: your-jwt-secret-key
      JWT_EXPIRES_IN: 7d
      NODE_ENV: test
      GOOGLE_CALLBACK: http://localhost:3000/api/auth/google/callback
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      FACEBOOK_CALLBACK: http://localhost:3000/api/auth/facebook/callback
      FACEBOOK_CLIENT_ID: sss
      FACEBOOK_CLIENT_SECRET: sss

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Copy ENV
        run: cp .env.example .env

      - name: Install dependencies
        run: yarn

      # - name: Delete all migrations except the initial schema
      #   run: |
      #     echo "Deleting migration directories except 20250423000000_initial_schema"
      #     find prisma/migrations -type d ! -name '20250423000000_initial_schema' -exec rm -rf {} +

      - name: Generate Prisma Client
        run: yarn prisma generate

      - name: Check Prisma Client
        run: cat node_modules/.prisma/client/index.d.ts | grep UserRole

      - name: Run Migrations
        run: yarn migrate

      - name: Seed the database
        run: yarn seed

      - name: Run Tests
        run: yarn run test
